name: ms3_extract

on:
  push:
    branches:
      - main
jobs:
  extract:
    if: github.event.pusher.name != 'ms3-bot'
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          path: main
      - name: Install ms3
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/johentsch/ms3.git@corpus_structure
      - name: Run ms3 extract
        working-directory: ./main
        run: |
          ms3 extract -M -N -X
      - name: Push files
        working-directory: ./main
        continue-on-error: true
        run: |
          git config --global user.name "ms3-bot"
          git config --global user.email dcml.annotators@epfl.ch
          git config --global user.token ${{ secrets.MS3_BOT_TOKEN }}
          git add -A
          git commit -m "Automatically added TSV files from parse with ms3"
          git push
      - name: Clone corpusstats
        uses: actions/checkout@v2
        with:
          repository: DCMLab/corpus_statistics_generator
          path: ./corpusstats
          ref: main
          token: ${{ secrets.MS3_BOT_MAINTENANCE  }}
      - name: Install corpusstats
        run: python -m pip install -e ./corpusstats
      - name: Generate GitHub pages
        working-directory: ./main
        run: |
          python .github/workflows/update_pages.py -g ${{ github.repository }} -t ${{ secrets.MS3_BOT_MAINTENANCE  }} -d tonicizations -o ../public
      - name: Display generated files
        working-directory: ./public
        run: ls
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: true
